name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, community
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          config_order: base.header, base.activity+community, leetcode, anilist
          config_display: medium
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_anilist: yes
          plugin_anilist_user: Moeblob
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 10
          plugin_anilist_shuffle: no
          extras_css: |
            .field svg {
            fill: #c692e9;
            }
            .field {
            color: #ad85d4;
            }
            h1, h2, h3 {
            color: #693f95 !important;
            }
          extras_js: |
            for (const {a, b} of [
             {a:"#216e39", b:"#693f95"},
             {a:"#30a14e", b:"#8357ad"},
             {a:"#40c463", b:"#9e70c5"},
             {a:"#9be9a8", b:"#b98ade"},
             {a:"#ebedf0", b:"#c692e9"},
             ])
             document.querySelectorAll(`svg g [fill="${a}"]`).forEach(node => node.setAttribute("fill", b))
          
          
