name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_anilist: yes
          plugin_anilist_user: Moeblob
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          extras_css: |
            .field svg {
            fill: #c692e9;
            }
            .field {
            color: #ad85d4;
            }
            h1, h2, h3 {
            color: #804fb3 !important;
            }
          
          
