name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          config_order: base.header, base.activity+community, base.repositories, habits, leetcode
          config_display: columns
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          extras_css: |
            .field svg {
            fill: #c692e9;
            }
            .field {
            color: #ad85d4;
            }
            h1, h2, h3 {
            color: #50326f !important;
            }
          extras_js: |
            for (const {a, b} of [
             {a:"#216e39", b:"#50326f"},
             {a:"#30a14e", b:"#6c498c"},
             {a:"#40c463", b:"#8960aa"},
             {a:"#9be9a8", b:"#a779c9"},
             {a:"#ebedf0", b:"#c692e9"},
             ])
             document.querySelectorAll(`svg g [fill="${a}"]`).forEach(node => node.setAttribute("fill", b))
          
          
